### ISSUE TITLE
[Question] Is there any way to get the Node in a Graph?

### ISSUE THREAD

**Issue by knrt10** [awalterschulze/gographviz#49]
I want to edit a node attributes inside a graph. Is there any way to get the node by name of node and edit it? Like in nodejs package [JNXnetwork](http://jsnetworkx.org/getting_started.html) we can do that by 

```js
G.node.get(0).foo = 'bar';
```
Is there anyway in this package to do that? 

Thanks

**Comment by awalterschulze** [comment]
If you are using the default [Graph](https://github.com/awalterschulze/gographviz/blob/master/graph.go#L23) then changing the name of a node is quite envolved, since the name is used as the identifier.
You would have to update references to the node, for example all edges made to the node.

You could use `gographviz.Analyse` to parse the graph into your own structure.
If you have an idea of how to do it better, for your use case.
This structure just needs to satisfy the [gographviz.Interface](https://github.com/awalterschulze/gographviz/blob/master/gographviz.go#L29).
You can then write out your graph, using the gographviz Graph.
See [this example](https://github.com/awalterschulze/gographviz/blob/da5c847b6fb13f2f76225f0ca9d912f5801d92e7/example_test.go#L120)

If you have an idea of how to do it better for all usecases, then let's discuss.
This might be something worthy of contributing, if you are interested.

**Comment by knrt10** [comment]
Thanks for replying @awalterschulze . So here is my case like I have a graph that is already created. With nodes like

```go
for _, val := range questionIDs {
	_ = G.AddNode("G", val, nil)
}
```

here questionsIDs is just a slice of string and  `G` is *\*graph.Graph*. So now I want to push another value inside my existing node inside graph `G` using a simple function 

```
pushPropertyToNode(G, target, "repeatRules", rule);
```

Can you suggest how should I do that? 

Thanks

**Comment by awalterschulze** [comment]
How would this look in graphviz / dot syntax?

**Comment by knrt10** [comment]
This is just for one node and edges were also added. After `pushPropertyToNode` I guess like this. 
```go
digraph G {
	test1 [repeatRules = somevalue]-> test2 ;
}
```

**Comment by awalterschulze** [comment]
I don't think repeatRules is a valid attribute https://www.graphviz.org/doc/info/attrs.html

**Comment by awalterschulze** [comment]
Maybe you want
```
digraph G {
	test1 [label = "repeatRules = somevalue"]-> test2 ;
}
```

**Comment by knrt10** [comment]
Ok, yes you are absolutely right but the main thing is I want to add it to an existing node. There is the main problem regarding that.

**Comment by awalterschulze** [comment]
In this case the label is applied to the edge, not the node
```go
G.AddEdge("test1", "test2", true, map[string]string{"label": "repeatRules = somevalue"}
```

**Comment by knrt10** [comment]
Thanks
